### ISSUE TITLE
Mermaid Diagram Text Unreadable When Using Light Mode

### ISSUE THREAD

**Issue by SnakeRelatedBusiness** [vhbelvadi/obsidian-carbon#3]
![image](https://github.com/user-attachments/assets/a4c1c98b-4b06-41ca-b9c8-34e39bf53ee8)

Black Background and Black Text

**Comment by vhbelvadi** [comment]
@WarlockOfTheStones Thanks for reporting this. It should be fixed in [0.7.0](https://github.com/vhbelvadi/obsidian-carbon/releases/tag/0.7.0) to which you can update from within Obsidian.

I'll close this issue for the time being but please feel free to let me know if you continue to face problems with this.
